- shell: nohup ssh -i /tmp/.im/{{IM_INFRASTRUCTURE_ID}}/ansible_key -N -f -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -D {{front_ip}}:9999 {{ansible_ssh_user}}@{{front_ip}} > /tmp/.step0 2>&1
  args:
	 creates: /tmp/.step0
  run_once: true
  ignore_errors: yes

- copy:
	content: |
		#! /bin/bash
		node="$1"
		[ -f /tmp/sshconnect.${node}.lock ] && [ -d /proc/`cat /tmp/sshconnect.${node}.lock` ] && exit
		echo $$ > /tmp/sshconnect.${node}.lock
		pid="nnn"; fails="0"
		while true; do
			ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ConnectTimeout=10 -i /tmp/.im/{{IM_INFRASTRUCTURE_ID}}/ansible_key $node grep -q 0100007F:270E /proc/net/tcp
			r="$?"
			if [ $r -eq 255 ] ; then
				fails="$(( fails + 1 ))"
				[ $fails -ge 3 ] && exit
			elif [ $r -ne 0 ] ; then
				test -d /proc/$pid && kill -9 $pid
				ssh -i /tmp/.im/{{IM_INFRASTRUCTURE_ID}}/ansible_key -N -f -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -R 9998:{{front_ip}}:9999 $node > /tmp/.ssh_$node 2>&1 &
				pid="$!"
			fi
			sleep 10
		done
	dest: /tmp/sshconnect.sh
	mode: 0755